### ISSUE TITLE
设置maximumDate后出现bug

### ISSUE THREAD

**Issue by yikibug** [xiaozhuxiong121/PGDatePicker#1]
设置maximumDate为当前日期后，当年份视图滑动到小于当前年时候，月份不能显示12个月，参考图如下：
![2017-09-05 10 19 08](https://user-images.githubusercontent.com/12478452/30065682-48af94f6-9288-11e7-85db-e6c7be4fdb56.png)

**Comment by xiaozhuxiong121** [comment]
已修复，pod update

**Comment by BeckWang0912** [comment]
设置最大最小日期后还有很多需要完善的地方
` picker.minimumDate = NSDate.setYear(1970, month: 1)
   picker.maximumDate = NSDate.setYear(2020, month: 1)`

<img width="408" alt="wx20170929-115430 2x" src="https://user-images.githubusercontent.com/26214723/31000266-fadb921a-a50c-11e7-948b-f49adb6f8a0d.png">

**Comment by xingyuniu** [comment]
设置多大年月日后，小于设置的最大月份的天数也只有设置的最大月份的设定的最大天数
![img_0292](https://user-images.githubusercontent.com/8209278/31874079-ece06136-b7f9-11e7-9042-4f3c841e7fb9.PNG)

**Comment by xiaozhuxiong121** [comment]
@xingyuniu 谢谢反馈，已经修复。
pod 'PGDatePicker', '>= 1.1.0'
pod update

**Comment by xiaozhuxiong121** [comment]
@BeckWang0912 
谢谢反馈，已经修复，请更新```pod update```
```
pod 'PGDatePicker', '>= 1.1.0'
```
如果```datePicker.datePickerMode = .date```，建议这样的方式去设置```minimumDate```和
```maximumDate```
```
datePicker.minimumDate = NSDate.setYear(2015, month: 5, day: 10)  
datePicker.maximumDate = NSDate.setYear(2020, month: 10, day: 20)
```
如果不设置```minimumDate```默认无穷小，同样，如果不设置```maximumDate```默认无穷大
