### ISSUE TITLE
重复调用show函数视图已有但是位置不正确

### ISSUE THREAD

**Issue by mysizeofcn** [xiaozhuxiong121/PGDatePicker#10]
作者大大好！
`[UIView animateWithDuration:0.3 animations:^{
        self.headerView.frame = CGRectMake(0, kScreenHeight - height - kHeaderViewHeight, kScreenWidth, kHeaderViewHeight);
        self.frame = CGRectMake(0, CGRectGetMaxY(self.headerView.frame), kScreenWidth, height);
    }];`

这段代码应该加在-show函数的结尾，而不应该在layoutsubviews，因为重复调用show的话，并没有弹出显示。。。

**Comment by xiaozhuxiong121** [comment]
如果需要多次弹出那么可以这么做
```
PGDatePicker *datePicker = [[PGDatePicker alloc]init];
datePicker.delegate = self;
[datePicker show];
```

```
PGDatePicker *datePicker = [[PGDatePicker alloc]init];
datePicker.delegate = self;
[datePicker show];
```

**Comment by mysizeofcn** [comment]
额，每次都需要alloc init好累，哈哈
