### ISSUE TITLE
再请问

### ISSUE THREAD

**Issue by q32784307** [xiaozhuxiong121/PGDatePicker#101]
我需要用到 时分周 的那种样式，
NSCalendar *gregorian = [[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar];
    NSDate *date = [gregorian dateFromComponents:dateComponents];
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init];
    [dateFormatter setDateFormat:@"MM-dd EEE HH:mm"];
    self.currentDateString = [dateFormatter stringFromDate:date];
这是我点击确定之后，获取到的时间转成字符串。然后我要根据我选择的时间，再次打开的时间记忆。

NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
    dateFormatter.dateFormat = @"MM-dd-EEE-HH-mm";
    NSDate *date = [dateFormatter dateFromString:self.currentDateString];
    [datePicker setDate:date animated:false];
但是这样好像不行啊，是不是格式不对

**Comment by xiaozhuxiong121** [comment]
`yyyy-MM-dd e HH:mm`
例如：
```
NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
dateFormatter.dateFormat = @"yyyy-MM-dd e HH:mm";
NSDate *date = [dateFormatter dateFromString: @"2018-08-23 5 14:01"];
[datePicker setDate:date animated:false];
```
