### ISSUE TITLE
关于确定和取消按钮的颜色设置.

### ISSUE THREAD

**Issue by MeteoriteMan** [xiaozhuxiong121/PGDatePicker#103]
可以在"PGDatePickManagerHeaderView"类中新增两个属性.然后懒加载这俩属性.在getter里头判断_color是否有.有就设置成有的,没有就设置成默认颜色

**Comment by MeteoriteMan** [comment]
可以在"PGDatePickManagerHeaderView"类中新增两个属性.然后懒加载这俩属性.在getter里头判断_color是否有.有就设置成有的,没有就设置成默认颜色

**Comment by xiaozhuxiong121** [comment]
THX，在2.5.5版本中已更新, pod update试试
