### ISSUE TITLE
设置默认时间无效！！！！

### ISSUE THREAD

**Issue by sunshineboy001** [xiaozhuxiong121/PGDatePicker#104]
[datePicker setDate:defaultDate animated:YES];
[datePicker show];
这样设置默认时间的，但是显示的效果为默认的最小时间，而不是设定的默认时间！是设置方式不对吗？还是咋弄？

**Comment by xiaozhuxiong121** [comment]
具体代码贴出来，我看看

**Comment by sunshineboy001** [comment]
晚上回去把代码贴出来，最近比较忙没时间来看。不好意思！

**Comment by sunshineboy001** [comment]
PGDatePicker *datePicker = [[PGDatePicker alloc]init];
    datePicker.tag = index;
    datePicker.delegate = self;
    datePicker.datePickerType = PGPickerViewType2;
    datePicker.isHiddenMiddleText = false;
    datePicker.datePickerMode = PGDatePickerModeDate;
    
    //得到当前的时间
    NSDate *currentDate = [NSDate date];
    
    NSString *currentDateStr = [APPDEL.user getCurrentDateStr];
    
    NSString *startDateString = [APPDEL.user getBeforeOrAfterDateFromDete:currentDateStr withYear:0 withMonth:6 withDay:0 withType:XXDateTypeBefore];
    
    NSString *endDateString = [APPDEL.user getBeforeOrAfterDateFromDete:currentDateStr withYear:0 withMonth:6 withDay:0 withType:XXDateTypeAfter];
    
    NSDate *defaultDate = currentDate;
    
    datePicker.minimumDate = [NSDate setYear:[[[startDateString componentsSeparatedByString:@"-"] objectAtIndex:0] integerValue] month:[[[startDateString componentsSeparatedByString:@"-"] objectAtIndex:1] integerValue] day:[[[startDateString componentsSeparatedByString:@"-"] objectAtIndex:2] integerValue]];
    datePicker.maximumDate = [NSDate setYear:[[[endDateString componentsSeparatedByString:@"-"] objectAtIndex:0] integerValue] month:[[[endDateString componentsSeparatedByString:@"-"] objectAtIndex:1] integerValue] day:[[[endDateString componentsSeparatedByString:@"-"] objectAtIndex:2] integerValue]];
    
    [datePicker setDate:defaultDate animated:YES];
    
    [datePicker show];
