### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by LiuSky** [xiaozhuxiong121/PGDatePicker#105]
1.能否直接让PGDatePickManager来掌控取消，以及确定事件。不然的话，变成取消是在一个地方，确定又变另外一个地方。
2.为什么要在界面弹出后，设置属性才生效。这个应该也很好处理。
如果需要的话，我可以提PR

**Comment by xiaozhuxiong121** [comment]
1、现在就是PGDatePickManager来控制取消跟确认按钮
2、什么属性是弹出界面后才生效
遇到什么问题了，把代码贴一下, btw, 如果有好的idea随时欢迎提交PR

**Comment by LiuSky** [comment]
1.我有点看不懂PGDatePickManager的业务逻辑：
 (1):取消按钮的话，有block可以了。
 (2):确定按钮的话，我还需要去设置PGDatePicker *datePicker的回调，然后才能拿到确定按钮。而不是在PGDatePickManager本身就直接提供confirmBlock。这个个人觉得结构很有问题了，最好的情况下PGDatePickManager 是为了让别人快捷调用，这时候应该直接提供一些属性跟一些回调，直接让外部操作，而不是PGDatePickManager 里面的属性的对象的属性。 （个人观点）
2.如图
<img width="682" alt="2018-08-06 12 25 44" src="https://user-images.githubusercontent.com/3087745/43697028-dc397870-9973-11e8-850d-7b8b59b73d6b.png">

**Comment by xiaozhuxiong121** [comment]
PGDatePickManager只是PGDatePicker上封装了一层UI，选中得到日期事件是PGDatePicker本身的属性，你需要选中得到日期，如果把选中日期的回调放到PGDatePickManager，那么自定义样式就没法实现了，你可以理解PGDatePicker跟UIDatePicker类似，而且除了代理回调也可以，
```
datePicker.selectedDate = ^(NSDateComponents *dateComponents) {};
```

**Comment by LiuSky** [comment]
<img width="754" alt="2018-08-07 11 11 18" src="https://user-images.githubusercontent.com/3087745/43752199-a8345e68-9a32-11e8-84cf-18ebfb23fdff.png">
