### ISSUE TITLE
您好,如果我要设置日时这种模式,我该怎么修改源码呢?麻烦您回复一下

### ISSUE THREAD

**Issue by LifeKingKong** [xiaozhuxiong121/PGDatePicker#107]
您好,如果我要设置日时这种模式,我该怎么修改源码呢?麻烦您回复一下!格式就是天数+小时

**Comment by xiaozhuxiong121** [comment]
天数+小时，那么天数应该是对应的当月的天数，大月的话31天，小月的话30天，还有闰年、二月等，都要判断，月日，或者时分 模式你都可以试着改改

**Comment by LifeKingKong** [comment]
好的,谢谢您!

**Comment by LifeKingKong** [comment]
您源码不是有个月日时的格式吗?我能不能直接修改数据源?不显示月这一列?直接显示日+时这两列呢?

**Comment by xiaozhuxiong121** [comment]
你可以尝试一下

**Comment by LifeKingKong** [comment]
参照您的样式我添加了这个dd HH格式的,但是设置最大最小值的时候没有成功.除了PGDatePickerView和一个类别文件,请问哪里还有需要对这个最大最小作修改的地方呢?

**Comment by xiaozhuxiong121** [comment]
`PGDatePicker`里面还要修改，你尝试一下

**Comment by LifeKingKong** [comment]
谢谢您,最近太忙没上gitHub,问你的第二天我就添加好了这一种类型,感谢作者的代码思路!
