### ISSUE TITLE
UI有问题，请调整

### ISSUE THREAD

**Issue by Danie1s** [xiaozhuxiong121/PGDatePicker#109]
如图，第一次打开的时候，并没有水平对齐

![image](https://user-images.githubusercontent.com/19432029/44380443-f7931600-a53d-11e8-8cd0-ffc281cb7e8f.png)

**Comment by xiaozhuxiong121** [comment]
贴一下代码，我看下

**Comment by xiaozhuxiong121** [comment]
`pod update` 试试

**Comment by Danie1s** [comment]
感谢你做出的努力，但是很遗憾地告诉你，就如上图一样 `2018 Y` 还是没完全水平对齐

**Comment by xiaozhuxiong121** [comment]
`pod update` 试试

**Comment by Danie1s** [comment]
可以了，谢谢
