### ISSUE TITLE
pod的版本不对

### ISSUE THREAD

**Issue by YangLiMey** [xiaozhuxiong121/PGDatePicker#110]

**Comment by xiaozhuxiong121** [comment]
why?

**Comment by YangLiMey** [comment]
你好，我现在直接 pod 'PGDatePicker',pod进来的是Installing PGDatePicker (1.0.8)
Installing PGPickerView (1.1.0)，感觉跟你写的不一样，不知道问题是在哪里

**Comment by YangLiMey** [comment]
重新pod了一下，已经到最新版本了，Installing PGDatePicker 2.5.5 (was 1.0.8)
Installing PGPickerView 1.3.1 (was 1.1.0)，但是跟说明文档上的不一样，我导入的是#import "PGDatePicker.h"
#import "PGDatePickManager.h"这两个头文件，文档上的头文件导入报错，不知道原因在哪里，现在正在使用，很感谢及时回复。

**Comment by xiaozhuxiong121** [comment]
pod update试试

**Comment by xiaozhuxiong121** [comment]
ok
