### ISSUE TITLE
设置默认时间无效！！！！

### ISSUE THREAD

**Issue by sunshineboy001** [xiaozhuxiong121/PGDatePicker#113]
这样设置默认时间的，但是显示的效果为默认的最小时间，而不是设定的默认时间！是设置方式不对吗？还是咋弄？
代码如下：
PGDatePicker *datePicker = [[PGDatePicker alloc]init];
    datePicker.tag = index;
    datePicker.delegate = self;
    datePicker.datePickerType = PGPickerViewType2;
    datePicker.isHiddenMiddleText = false;
    datePicker.datePickerMode = PGDatePickerModeDate;
    
    //得到当前的时间
    NSDate *currentDate = [NSDate date];
    
    NSString *currentDateStr = [APPDEL.user getCurrentDateStr];
    
    NSString *startDateString = [APPDEL.user getBeforeOrAfterDateFromDete:currentDateStr withYear:0 withMonth:6 withDay:0 withType:XXDateTypeBefore];
    
    NSString *endDateString = [APPDEL.user getBeforeOrAfterDateFromDete:currentDateStr withYear:0 withMonth:6 withDay:0 withType:XXDateTypeAfter];
    
    NSDate *defaultDate = currentDate;
    
    datePicker.minimumDate = [NSDate setYear:[[[startDateString componentsSeparatedByString:@"-"] objectAtIndex:0] integerValue] month:[[[startDateString componentsSeparatedByString:@"-"] objectAtIndex:1] integerValue] day:[[[startDateString componentsSeparatedByString:@"-"] objectAtIndex:2] integerValue]];
    datePicker.maximumDate = [NSDate setYear:[[[endDateString componentsSeparatedByString:@"-"] objectAtIndex:0] integerValue] month:[[[endDateString componentsSeparatedByString:@"-"] objectAtIndex:1] integerValue] day:[[[endDateString componentsSeparatedByString:@"-"] objectAtIndex:2] integerValue]];
    
    [datePicker setDate:defaultDate animated:YES];
    
    [datePicker show];

**Comment by xiaozhuxiong121** [comment]
目前最新版本是`2.5.6`,你看下是不是最新版本

**Comment by sunshineboy001** [comment]
查看最新版本为2.4.4呀，没你说的2.5.6
PGDatePicker (2.4.4)
   日期选择器
   pod 'PGDatePicker', '~> 2.4.4'
   - Homepage: https://github.com/xiaozhuxiong121/PGDatePicker
   - Source:   https://github.com/xiaozhuxiong121/PGDatePicker.git
   - Versions: 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.0, 2.2.2, 2.2.1, 2.2.0, 2.1.0, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0, 1.5.13, 1.5.12, 1.5.11, 1.5.10, 1.5.9, 1.5.8, 1.5.7, 1.5.6, 1.5.5, 1.5.4, 1.5.3, 1.5.2, 1.5.1,
   1.5.0, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.0, 1.2.1, 1.2.0, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1 [master repo]

**Comment by xiaozhuxiong121** [comment]
`pod update`试试
