### ISSUE TITLE
加载比较慢，可以优化吗

### ISSUE THREAD

**Issue by jkwf** [xiaozhuxiong121/PGDatePicker#114]
PGDatePickManager *datePickManager = [[PGDatePickManager alloc]init];
        datePickManager.isShadeBackgroud = true;
        PGDatePicker *datePicker = datePickManager.datePicker;
        datePicker.delegate = self;
        datePicker.datePickerType = PGPickerViewType1;
        datePicker.datePickerMode = PGDatePickerModeDateHourMinute;
        [self presentViewController:datePickManager animated:false completion:nil];

**Comment by xiaozhuxiong121** [comment]
目前来说使用的是`UITableView `复用的形式，我之后再想想看还有没有其他的方式去优化了

**Comment by xiaozhuxiong121** [comment]
更新到`2.6.6`试试
`pod update`
