### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by Vutumn** [xiaozhuxiong121/PGDatePicker#115]
当我选择2018 7 31号，点击确定。然后在把得到2018 7 31这个date对象用setdate给控件赋值，点进去查看控件的显示日期，发现时间停在了2018 7 1号。

**Comment by Vutumn** [comment]
这个bug是如果选择的日期超过了当月的日期数，就会默认到一号去。如如果当月是10月，只有10天，那么我选择9月超过10号的天数，然后设置日期，再次打开控件发现到了9月1日，发现是由于pgdatepicker里面的setupPickerView方法先判断了setdate设置了selectComponents然后在判断max和min重置了selectComponents导致，我的做法是调换一下判断先后就行了，目前未发现什么问题。

**Comment by Vutumn** [comment]
if (self.currentComponents.year == self.minimumComponents.year && self.currentComponents.month != self.minimumComponents.month) {
           self.selectComponents.month = self.maximumComponents.month;
      }

这个判断有问题

**Comment by xiaozhuxiong121** [comment]
更新到`2.6.6`试试
`pod update`
