### ISSUE TITLE
点击StatusBar滚到顶部，autoSelected无效

### ISSUE THREAD

**Issue by Eric1143** [xiaozhuxiong121/PGDatePicker#116]
autoSelected设为yes，但是点击状态栏日期滚到顶部不会触发didSelectDate方法，求解决，或者禁止tableView的scrollsToTop属性

**Comment by Eric1143** [comment]
scrollsToTop没有设为false，默认true，我点击状态栏可以滚到顶部

**Comment by xiaozhuxiong121** [comment]
更新到`2.6.7`试试
`pod update`
