### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by hxlailfh1314** [xiaozhuxiong121/PGDatePicker#117]
设置默认显示日期 会显示错误。
/**
 年月日
 */
- (IBAction)dateHandler:(id)sender {
    PGDatePickManager *datePickManager = [[PGDatePickManager alloc]init];
    datePickManager.isShadeBackgroud = true;
    PGDatePicker *datePicker = datePickManager.datePicker;
    datePicker.delegate = self;
    datePicker.datePickerType = PGPickerViewType1;
    datePicker.isHiddenMiddleText = false;
    datePicker.datePickerMode = PGDatePickerModeDate;
    [self presentViewController:datePickManager animated:false completion:nil];
    
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
    dateFormatter.dateFormat = @"yyyy-MM-dd";
    
//    datePicker.minimumDate = [dateFormatter dateFromString: @"2018-02-18"];
//    datePicker.maximumDate = [dateFormatter dateFromString: @"2020-01-18"];
    
    NSDate *date = [dateFormatter dateFromString: @"2019-01-18"];
    [datePicker setDate:date animated:true];
}

**Comment by codewine** [comment]
setDate 滑动不到目标未知，我看好多issue都是说这个问题

**Comment by codewine** [comment]
setDate 滑动不到目标位置，我看好多issue都是说这个问题

**Comment by xiaozhuxiong121** [comment]
更新到`2.6.6`试试
`pod update`
