### ISSUE TITLE
sometimes it crashed when call -[PGDatePicker yearList]

### ISSUE THREAD

**Issue by CroPort** [xiaozhuxiong121/PGDatePicker#128]
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderArray initWithCapacity:]: capacity (18446744073709549746) is ridiculous

0 | CoreFoundation | __exceptionPreprocess-- | -- | --
1 | libobjc.A.dylib | objc_exception_throw
2 | CoreFoundation | _CFArgv
3 | CoreFoundation | -[__NSPlaceholderArray initWithCapacity:]
4 | CoreFoundation | +[NSMutableArray arrayWithCapacity:]
5 | PGDatePicker | PGDatePicker.m line 2057-[PGDatePicker yearList]
6 | PGDatePicker | PGDatePicker.m line 812-[PGDatePicker setDayListForMonthDays:]
7 | PGDatePicker | PGDatePicker.m line 121-[PGDatePicker setupPickerView]
8 | PGDatePicker | PGDatePicker.m line 95-[PGDatePicker layoutSubviews]

**Comment by GovernLu** [comment]
I have same problem！

**Comment by xiaozhuxiong121** [comment]
@CroPort @GovernLu could you send the code here?

**Comment by GovernLu** [comment]
> @CroPort @GovernLu could you send the code here?

不是必现的问题，只是Crashlytics上抓到崩溃报告了。我看代码里是没有做异常值判断。
- (NSArray *)yearList {
    if (!_yearList) {
        NSInteger index = self.maximumComponents.year - self.minimumComponents.year;
        NSMutableArray *years = [NSMutableArray arrayWithCapacity:index];
        for (NSUInteger i = self.minimumComponents.year; i <= self.maximumComponents.year; i++) {
            [years addObject:[@(i) stringValue]];
        }
        _yearList = years;
    }
    return _yearList;
}
因为index是Integer类型，而创建数组传的是UInteger，如果index是负数就会引起这个问题，我算了一下是-1870。我在用的时候设置了最小值是1900-01-01，最大值是[NSDate date]。我猜测是NSDate的API偶尔出现bug了。你设置的最小时间比最大时间大的话，也会崩溃。

**Comment by xiaozhuxiong121** [comment]
更新到`2.6.6`试试
`pod update`

**Comment by GovernLu** [comment]
复现步骤：将系统日历设为日本历
