### ISSUE TITLE
能不能加个功能

### ISSUE THREAD

**Issue by LXJason** [xiaozhuxiong121/PGDatePicker#13]
希望大神加个  年-月-第几周...已Star  谢谢大神

**Comment by xiaozhuxiong121** [comment]
🤝平时忙的没有时间🤦‍♀️，这周末加好了告诉你

**Comment by DSZ911226** [comment]
大神，关于setDate 的animated 为yes 的时候 问题，还没有完全处理好，年月日的时候的年是随机的效果

**Comment by xiaozhuxiong121** [comment]
@DSZ911226 好的， 我看看

**Comment by xiaozhuxiong121** [comment]
@DSZ911226 在`1.5.3`版本中已经修复

**Comment by xiaozhuxiong121** [comment]
@LXJason 在`Dev`分支上已经添加，请查看[Dev](https://github.com/xiaozhuxiong121/PGDatePicker/tree/Dev),
由于设置最大值，最小值还有点问题，所以没有推送到`master`分支上，后期有时间了会继续优化的

**Comment by SarahCarrie** [comment]
设置了最小值，最大值，发现选择器对应的选中日期不是setDate的mouth

**Comment by xiaozhuxiong121** [comment]
@SarahCarrie 贴一下相关代码

**Comment by SarahCarrie** [comment]
- (void)showDatePicker:(NSString *)date minDate:(NSDate *)mindate maxDate:(NSDate *)maxdate finishSelectBlock:(SelectedBlock)selectBlock {
    
    PGDatePickManager *datePickManager = [[PGDatePickManager alloc]init];
    datePickManager.isShadeBackgroud = true;
    PGDatePicker *datePicker = datePickManager.datePicker;
    datePicker.delegate = self;
    datePicker.datePickerType = PGPickerViewType1;
    datePicker.datePickerMode = PGDatePickerModeDateHourMinute;
    if (maxdate) {
        [datePicker setMaximumDate:maxdate];
    }
    if (mindate) {
        [datePicker setMinimumDate:mindate];
    }
    [datePicker setDate:[self getDateForm:date]];
    [_viewController presentViewController:datePickManager animated:false completion:nil];
    
    self.selectedBlock = selectBlock;
}

**Comment by SarahCarrie** [comment]
我改成这样if (self.minimumDate || self.maximumDate) {
        if (self.selectComponents.year < self.minimumComponents.year) {
            self.selectComponents.year = self.minimumComponents.year;
            self.selectComponents.month = self.minimumComponents.month;
            self.selectComponents.day = self.minimumComponents.day;
            self.selectComponents.hour = self.minimumComponents.hour;
            self.selectComponents.minute = self.minimumComponents.minute;
            self.selectComponents.second = self.minimumComponents.second;
        }else if (self.selectComponents.year > self.maximumComponents.year) {
            self.selectComponents.year = self.maximumComponents.year;
            self.selectComponents.month = self.maximumComponents.month;
        }else if (self.selectComponents.year == self.minimumComponents.year) {
//            self.selectComponents.month = self.minimumComponents.month;
        }
        NSInteger day = [self howManyDaysWithMonthInThisYear:self.selectComponents.year withMonth:self.selectComponents.month];
        [self setDayListForMonthDays:day];
    }，就可以了，不会出现

**Comment by xiaozhuxiong121** [comment]
maxdate、mindate、[self getDateForm:date]这三个的值发下，我看下

**Comment by xiaozhuxiong121** [comment]
@SarahCarrie 把maxdate、mindate、[self getDateForm:date]这三个的值发下，我看下

**Comment by SarahCarrie** [comment]
哈哈，
![42fe2be20f12844480de3979962267fe](https://user-images.githubusercontent.com/8305735/36059594-419d01f2-0e76-11e8-8b67-1ffe455581f3.jpg)

**Comment by SarahCarrie** [comment]
最小值是2018年1月11 15:18，我setdate是2018年2月10日

**Comment by SarahCarrie** [comment]
setDate如果是2018年的，选中都是最小值的month

**Comment by xiaozhuxiong121** [comment]
@SarahCarrie 刚修复，更新到`2.0.7`版本试试
