### ISSUE TITLE
还是Picker滚动位置错误问题，实际在12月，却滚到了11月。

### ISSUE THREAD

**Issue by linkfei** [xiaozhuxiong121/PGDatePicker#134]
<img width="317" alt="1" src="https://user-images.githubusercontent.com/12987627/49879041-10fcfc80-fe64-11e8-870e-d47ff8e73d65.png">

**Comment by linkfei** [comment]
是最新 2.6.0版本。

**Comment by linkfei** [comment]
```


        let picker = PGDatePickManager()
        
        picker.titleLabel.text = "选择日期"
        //设置头部的背景颜色
        picker.headerViewBackgroundColor = UIColor.tint
        
        //设置半透明背景
        picker.isShadeBackgroud = true
        picker.headerHeight = 50
        
        //设置取消按钮的字体颜色
        picker.cancelButtonTextColor = UIColor.lightGray
        //设置取消按钮的字
        //        picker.cancelButtonText = "取消"
        //设置取消按钮的字体大小
        picker.cancelButtonFont = UIFont.boldSystemFont(ofSize: 17)
        
        //设置确定按钮的字体颜色
        picker.confirmButtonTextColor = UIColor.tint
        //设置确定按钮的字
        //        picker.confirmButtonText = "确定"
        //设置确定按钮的字体大小
        picker.confirmButtonFont = UIFont.boldSystemFont(ofSize: 17)
        
        let datePicker = picker.datePicker!
        datePicker.delegate = self
        datePicker.isHiddenMiddleText = false
        datePicker.datePickerMode = .dateHourMinute
        
        switch self.showType {
        case .time:
            datePicker.setDate(self.item?.endTime ?? Date())
            break
        case .hourMinute:
            //datePicker.setDate(selectedDate ?? Date())
            datePicker.setDate(self.item?.remindTime ?? Date(), animated: true)
            
            break
        }


        //设置线条的颜色
        datePicker.lineBackgroundColor = UIColor.groupTableViewBackground
        //设置选中行的字体颜色
        datePicker.textColorOfSelectedRow = UIColor.tint
        //设置未选中行的字体颜色
        datePicker.textColorOfOtherRow = UIColor.lightGray
        
        self.present(picker, animated: false, completion: nil)

```

**Comment by SummerHF** [comment]
同样的问题 设置了12月份 却显示11月份

**Comment by deanli08** [comment]
是的。。看效果是创建之后本来是12月 自动跳转到11月了。

**Comment by xiaozhuxiong121** [comment]
好的，我检查一下

**Comment by deanli08** [comment]
- (PGDatePicker *)datePicker1{
    if (!_datePicker1) {
        _datePicker1 = [[PGDatePicker alloc] init];
        _datePicker1.autoSelected = YES;
//        _datePicker1.rowHeight = RatioHeight(40);
        _datePicker1.minimumDate = [NSDate date];
        _datePicker1.maximumDate = [[NSDate date] dateByAddingDays:365*5];
//        NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
//            dateFormatter.dateFormat = @"yyyy-MM-dd";
//        _datePicker1.minimumDate = [dateFormatter dateFromString: @"2018-02-18"];
        _datePicker1.textFontOfSelectedRow = LDAutoFont(12);
        _datePicker1.textFontOfOtherRow = LDAutoFont(12);
        _datePicker1.textColorOfOtherRow = UIColor.blackColor;// RGBA(195, 195, 195, 1);
        _datePicker1.textColorOfSelectedRow = LDOrangerColor;
        _datePicker1.lineBackgroundColor = LDOrangerColor;
        _datePicker1.datePickerMode = PGDatePickerModeDateHourMinuteSecond;
        _datePicker1.delegate = self;
        _datePicker1.isHiddenMiddleText = YES;
    }
    return _datePicker1;
}
- (void)layoutSubviews{
    [super layoutSubviews];
    self.datePicker1.frame = self.bounds;
}

只能这样搞了
    [self addSubview:self.datePicker1];
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(.35 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [self.datePicker1 setDate:[NSDate date] animated:YES];
        });
但是偶尔还是会出现 弹出picker 选中的是11月。日也有几率错，比如今天是12月13日，但是默认弹出12月12日

**Comment by xiaozhuxiong121** [comment]
我用demo测试了几遍都没有出现，是怎么操作才会发生的呢？

**Comment by linkfei** [comment]
就是随机出现啊。 每次弹出时候走上面这段代码。

**Comment by xiaozhuxiong121** [comment]
@deanli08 如果可以的话，你能把你的测试步骤说下么，或者提供一个demo，视频之类的，我看看

**Comment by Axk520** [comment]
确实日期会滚动错位， 我用的模拟器   年月日格式  传的同样的日期  有时候正确 有时候月和日某一个就错位一个

**Comment by deanli08** [comment]
> @deanli08 如果可以的话，你能把你的测试步骤说下么，或者提供一个demo，视频之类的，我看看

已经弄个了 简单的demo 你看看 ，是自定义的View然后添加的picker。

**Comment by Axk520** [comment]
[datePicker setDate:currentDate  animated:YES];    YES时是正确的
        [datePicker setDate:currentDate  animated:NO];      NO时就错误了

**Comment by xiaozhuxiong121** [comment]
@deanli08 demo在哪呢？

**Comment by deanli08** [comment]
> @deanli08 demo在哪呢？
piggybear_net@163.com 发送到这个邮箱了

**Comment by deanli08** [comment]
[PGDatePicker-master 2.zip](https://github.com/xiaozhuxiong121/PGDatePicker/files/2684624/PGDatePicker-master.2.zip)

**Comment by xiaozhuxiong121** [comment]
@deanli08非常感谢提供的demo
 @linkfei @SummerHF @Axk520 
`pod update ` 试试
```
PGPickerView(1.3.5)
PGDatePicker(2.6.0)
```

**Comment by xiaozhuxiong121** [comment]
大家 `pod update`试试

`PGPickerView` 最新版 `1.3.5`
`PGDatePicker` 最新版 `2.6.0`

好或者没有好都说一下，谢谢啦

**Comment by deanli08** [comment]
@xiaozhuxiong121
更新了最新的PGPickerView 1.3.5  这个问题解决了试了一会 没有出现

**Comment by deanli08** [comment]
我又发现了新的问题。还是刚才给你的demo，如果把row高度设置为30.会出现滚动出去的情况
 _datePicker1 = [[PGDatePicker alloc]init];
        _datePicker1.autoSelected = YES;
        _datePicker1.rowHeight = 30;
        _datePicker1.datePickerMode = PGDatePickerModeDate;
        _datePicker1.delegate = self;
        _datePicker1.isHiddenMiddleText = YES;

![3931545031957_ pic](https://user-images.githubusercontent.com/11403708/50072661-00a4a300-0211-11e9-97b5-a48cd54557b0.jpg)

**Comment by xiaozhuxiong121** [comment]
@deanli08 我用demo测试了一下没有问题，rowHeight = 30;
你在检查下代码看看哪里设置的有问题

**Comment by deanli08** [comment]
[PGDatePicker-master 2 2.zip](https://github.com/xiaozhuxiong121/PGDatePicker/files/2685016/PGDatePicker-master.2.2.zip)
@xiaozhuxiong121  试试这个demo，我在模拟器真机上都出现了 刚弹出来这样的
![image](https://user-images.githubusercontent.com/11403708/50074486-12894480-0217-11e9-80c4-032341de0f3c.png)、
然后滚动 
![image](https://user-images.githubusercontent.com/11403708/50074520-259c1480-0217-11e9-9c96-5876834bd7f9.png)

**Comment by xiaozhuxiong121** [comment]
我的意思是直接用我的demo, 然后把rowHeight设置为30，也会出现吗?

**Comment by deanli08** [comment]
用你的没有，好纳闷。只是把PGDatePicker单独拿出来放在弹出PopView 里面就有问题，我看你demo 是在controller 里面，这个还没试

**Comment by xiaozhuxiong121** [comment]
应该是PGDatePicker frame设置的有问题吧，你在检查一下，如果还有问题开一个新的issue，这个滚动没有问题了，我就关了

**Comment by linkfei** [comment]
我更新了下 pod 的 PGPickerView 到1.3.5，setData 时候 animated = true 确实好了，可能是你这版本修改的延迟有效。

**Comment by linkfei** [comment]
@xiaozhuxiong121  还是谢谢你。

**Comment by xiaozhuxiong121** [comment]
@linkfei 不用谢，应该做的，就是延时的原因，因为弹出来的话iOS有个动画时间，要确保完全弹出来才能保证正确，所以有延时处理
