### ISSUE TITLE
月日周 时分 设置minimumDate崩溃

### ISSUE THREAD

**Issue by yuefeidragon** [xiaozhuxiong121/PGDatePicker#135]

**Comment by yuefeidragon** [comment]
应该怎么设置啊 我给date会崩溃 是现在12月份的原因吧 报错数组越界 
reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 11 beyond bounds [0 .. 0]'
崩在PGDatePicker.m 里 1327行

**Comment by xiaozhuxiong121** [comment]
更新到2.6.1试试
`pod update`
