### ISSUE TITLE
PGDatePicker.podspec依赖PGPickerView模块没有指定版本

### ISSUE THREAD

**Issue by aluoshuai** [xiaozhuxiong121/PGDatePicker#143]
在podspec配置中对依赖库没有做比较好的兼容，，例如老版本为【s.dependency 'PGDatePicker', '2.5.5'】，我在使用了【pod update】之后PGDatePicker没有进行更新，依赖的PGPickerView库进行了更新，所以造成了不兼容情况，导致项目无法正常运行

**Comment by xiaozhuxiong121** [comment]
PGDatePicker用的都是PGPickerView最新版，如果升级新版本的话，对应的改下变化就可以了
