### ISSUE TITLE
性能方面的建议。

### ISSUE THREAD

**Issue by laoSanDr** [xiaozhuxiong121/PGDatePicker#15]
![2b7fc9ec-8212-414e-8906-0b7ef0ce5ec4](https://user-images.githubusercontent.com/15378738/33057630-d3701f00-cec6-11e7-90f6-d04230beb018.png)

如图，每一条cell都重复创建了三次，这里是否可以优化一下。

**Comment by xiaozhuxiong121** [comment]
不是重复创建了3次，就是3个TableView组合的

**Comment by laoSanDr** [comment]
刚开始没仔细看，现在明白了，谢谢。
