### ISSUE TITLE
2月选择返回3月 这个什么时候修改一下

### ISSUE THREAD

**Issue by wd12121213** [xiaozhuxiong121/PGDatePicker#151]

**Comment by xiaozhuxiong121** [comment]
贴一下代码谢谢

**Comment by wd12121213** [comment]
PGDatePickManager *datePickManager = [[PGDatePickManager alloc]init];
    PGDatePicker *datePicker = datePickManager.datePicker;
    datePicker.delegate = self;
    datePicker.datePickerMode = PGDatePickerModeYearAndMonth;
    [self presentViewController:datePickManager animated:false completion:nil];
    
    datePickManager.titleLabel.text = @"请选择日期";
    //设置半透明的背景颜色
    datePickManager.isShadeBackground = true;
    //设置头部的背景颜色
    datePickManager.headerViewBackgroundColor = ColorWithHexString(@"EFEFEF");
    //设置线条的颜色
    datePicker.lineBackgroundColor = DesignBrown;
    //设置选中行的字体颜色
    datePicker.textColorOfSelectedRow = [UIColor blackColor];
    //设置未选中行的字体颜色
    datePicker.textColorOfOtherRow = LightGray;
    //设置取消按钮的字体颜色
    datePickManager.cancelButtonTextColor = DesignBrown;
    //设置确定按钮的字体颜色
    datePickManager.confirmButtonTextColor = DesignBrown;

**Comment by wd12121213** [comment]
更新了最新的2.6.9  这个问题还是没解决

**Comment by wd12121213** [comment]
NSDate *date = [NSDate setYear:dateComponents.year month:dateComponents.month];
你好 我发现是这个set方法的问题  返回日期(lldb) po date
2019-03-01 16:00:00 +0000

**Comment by xiaozhuxiong121** [comment]
我用demo跑没有问题啊，另外升级报错类型改一下就好了，可以参考demo

**Comment by wd12121213** [comment]
你类目封装方法 有问题 返回的//    NSDate *date = [NSDate setYear:dateComponents.year month:dateComponents.month];  计算的date 有问题
