### ISSUE TITLE
find bug

### ISSUE THREAD

**Issue by gyyxiaogao** [xiaozhuxiong121/PGDatePicker#17]
![Uploading Snip20171123_14.png…]()

**Comment by gyyxiaogao** [comment]
![snip20171123_14](https://user-images.githubusercontent.com/16957066/33205077-9958dbb4-d140-11e7-8569-5b69a558a133.png)

**Comment by gyyxiaogao** [comment]
前天下的,最新版的

**Comment by xiaozhuxiong121** [comment]
`pod 'PGDatePicker', '>= 1.5.4'`
`pod update`
试试
