### ISSUE TITLE
设置最小的天数发现没有用，调试发现代码中你过滤掉了最小的天数

### ISSUE THREAD

**Issue by Abnerzj** [xiaozhuxiong121/PGDatePicker#18]
`- (void)setDayListForMonthDays:(NSInteger)day {
    NSMutableArray *days = [NSMutableArray arrayWithCapacity:day];
    NSInteger minDay = self.minimumComponents.day, maxDay = self.maximumComponents.day;
    if (self.currentComponents.year == self.maximumComponents.year) {
        if (self.currentComponents.month == self.maximumComponents.month) {
            day = maxDay;
        }
    }
    if (_setDate) {
        minDay = 1;
    }
   // 此处 i 的值应为minDay
    for (NSUInteger i = 1; i <= day; i++) {
        [days addObject:[@(i) stringValue]];
    }
    self.dayList = days;
}`

**Comment by xiaozhuxiong121** [comment]
当前版本是`1.5.4`，我测试了一下是可以的，你`pod update`试试

**Comment by Abnerzj** [comment]
我是直接从GitHub下载整个包的哦

**Comment by Abnerzj** [comment]
小时和分钟设置最小的值也没有用，我已经做了处理，秒我这边没用到就先没处理了。

**Comment by xiaozhuxiong121** [comment]
我这边把每个模式都测试了一遍，都是没有问题的，你能把你使用`PGDatePicker`的代码以及出现的问题截图贴一下么

**Comment by Abnerzj** [comment]
不好意思，这几天一直没上GitHub。我这边的需求是让用户选择一个时间，但是时间范围限制在从现在开始的三天：今天、明天、后天，针对小时和分也要从当前时间开始。下面的截图是我调整后的情况。
![2017-11-29 2 53 34](https://user-images.githubusercontent.com/7877559/33361948-1e8454d0-d515-11e7-9df5-79625811af4c.png)

**Comment by xiaozhuxiong121** [comment]
现在好了吗？

**Comment by Abnerzj** [comment]
因为我调整后没问题，所以没有更新最新的库了。

**Comment by xiaozhuxiong121** [comment]
ok
