### ISSUE TITLE
渲染很耗时

### ISSUE THREAD

**Issue by Jacky-LinPeng** [xiaozhuxiong121/PGDatePicker#180]
假如一个页面有两个 Picker对象 页面加载出来很慢，其他人有反馈这个问题吗？

**Comment by Jacky-LinPeng** [comment]
排查了代码 发现这里是这里很耗性能 ： daysWithMonthInThisYear 

官方文档：
“Creating a date formatter is not a cheap operation. If you are likely to use a formatter frequently, it is typically more efficient to cache a single instance than to create and dispose of multiple instances. One approach is to use a static
variable.”

**Comment by CoderJackySong** [comment]
我也发现了界面加载过慢的情况，请问现在是怎么处理的呢？

**Comment by Jacky-LinPeng** [comment]
> 我也发现了界面加载过慢的情况，请问现在是怎么处理的呢？

formatter 弄错单例呗 再加个字典缓存一下

**Comment by xiasanlan** [comment]
- (NSInteger)daysWithMonthInThisYear:(NSInteger)year withMonth:(NSInteger)month {
    BOOL isLeapYear = false;
    if((year % 400 == 0) || ((year % 4 == 0) && (year % 100 != 0))){
        isLeapYear = true ;
    }
    NSArray *days = @[@"31",isLeapYear?@"29":@"28",@"31",@"30",@"31",@"30",@"31",@"31",@"30",@"31",@"30",@"31"];
    return [days[month - 1] integerValue];
}
