### ISSUE TITLE
排查了代码 发现这里是这里很耗性能 ： daysWithMonthInThisYear

### ISSUE THREAD

**Issue by CoderJackySong** [xiaozhuxiong121/PGDatePicker#181]
排查了代码 发现这里是这里很耗性能 ： daysWithMonthInThisYear 

官方文档：
“Creating a date formatter is not a cheap operation. If you are likely to use a formatter frequently, it is typically more efficient to cache a single instance than to create and dispose of multiple instances. One approach is to use a static
variable.”

_Originally posted by @Jacky-LinPeng in https://github.com/xiaozhuxiong121/PGDatePicker/issues/180#issuecomment-607677524_

**Comment by xiasanlan** [comment]
- (NSInteger)daysWithMonthInThisYear:(NSInteger)year withMonth:(NSInteger)month {
    BOOL isLeapYear = false;
    if((year % 400 == 0) || ((year % 4 == 0) && (year % 100 != 0))){
        isLeapYear = true ;
    }
    NSArray *days = @[@"31",isLeapYear?@"29":@"28",@"31",@"30",@"31",@"30",@"31",@"31",@"30",@"31",@"30",@"31"];
    return [days[month - 1] integerValue];
}
