### ISSUE TITLE
不能比较时间大小

### ISSUE THREAD

**Issue by gyyxiaogao** [xiaozhuxiong121/PGDatePicker#19]

**Comment by xiaozhuxiong121** [comment]
什么意思

**Comment by gyyxiaogao** [comment]
![snip20171127_5](https://user-images.githubusercontent.com/16957066/33263988-bf48c934-d3a6-11e7-9900-f269c1577f9f.png)
后面的时间比前面的时间小,是不符合要求的.

**Comment by xiaozhuxiong121** [comment]
没太明白什么意思，是我这边的问题吗，能具体描述一下么
