### ISSUE TITLE
动态设置最小值最大值存在异常

### ISSUE THREAD

**Issue by OCAndSwift** [xiaozhuxiong121/PGDatePicker#20]
if self.maxEndDate != nil {
            datePicker.maximumDate = self.maxEndDate!
        }
if self.minEndDate != nil {
          datePicker.minimumDate = self.minEndDate!
        }

这样动态的设置区间最大值为默认值加六个月 最小值加一个月 为什么最小值设置正常 最大值设置失败呢?
但是加六个跨年后 设置的区间却是正确的。 不跨年所有情况都是直接显示到12月份

**Comment by xiaozhuxiong121** [comment]
`maximumDate`和`minimumDate`的具体值发下，我看下

**Comment by OCAndSwift** [comment]
func datePicker(_ datePicker: PGDatePicker!, didSelectDate dateComponents: DateComponents!) {
        print("dateComponents = ", dateComponents)
//        var component = DateComponents.init()
//        component.timeZone = TimeZone.current
//        component.year = dateComponents.year
//        component.month = dateComponents.month
        
        let date = Calendar.current.date(from: dateComponents)!
        print("选中日期= \(date)")
        
        if datePicker.tag == 100 {
            beginDate = date
            self.minEndDate = Calendar.current.date(byAdding: Calendar.Component.month, value: 1, to: date)
            self.maxEndDate = Calendar.current.date(byAdding: Calendar.Component.month, value: maxMonth, to: date)
            endDate = self.minEndDate
        }else if datePicker.tag == 101 {
            endDate = date
        }
        tableView.reloadSections(IndexSet.init(integer: 0), with: .automatic)
    }

根据选择的beginDate值 待下次点击显示选择视图的时候再次创建赋值
func getEndTime() {
        let datePicker = PGDatePicker()
        datePicker.tag = 101
        datePicker.delegate = self
        datePicker.datePickerMode = .yearAndMonth
        if self.maxEndDate != nil {
            datePicker.maximumDate = self.maxEndDate!
        }
        if self.minEndDate != nil {
            datePicker.minimumDate = self.minEndDate!
        }
        if endDate != nil {
            datePicker.setDate(endDate, animated: true)
        }
        datePicker.show()
    }
这时候展示的时间区间就出现异常了 好奇的就是最小值可以  跨年了也是OK的

**Comment by xiaozhuxiong121** [comment]
把`maximumDate`和`minimumDate`设置的具体值发下，比如
```
datePicker.minimumDate = NSDate.setYear(2015, month: 5)
datePicker.maximumDate = NSDate.setYear(2020, month: 10)
```
`minimumDate`是`2015-05`
`maximumDate`是`2020-10`
这样具体的日期，然后我好看下在这样的日期内，显示不正常的原因到底是什么

**Comment by OCAndSwift** [comment]
上面赋值的方法中不是有吗? 我是赋值动态的变量的 不是NSDate.setYear(2015, month: 5) 而是直接给了一个Date类型的值
func getEndTime() {
let datePicker = PGDatePicker()
datePicker.tag = 101
datePicker.delegate = self
datePicker.datePickerMode = .yearAndMonth
if self.maxEndDate != nil {
datePicker.maximumDate = self.maxEndDate!
}
if self.minEndDate != nil {
datePicker.minimumDate = self.minEndDate!
}
if endDate != nil {
datePicker.setDate(endDate, animated: true)
}
datePicker.show()
}

**Comment by OCAndSwift** [comment]
我的值不是定值 所以就没使用NSDate.setYear(2015, month: 5)  赋值

**Comment by xiaozhuxiong121** [comment]
```
if self.maxEndDate != nil {
datePicker.maximumDate = self.maxEndDate!
}
if self.minEndDate != nil {
datePicker.minimumDate = self.minEndDate!
}
if endDate != nil {
datePicker.setDate(endDate, animated: true)
}
```
我知道这样是动态的赋值，我的意思是在显示不正确的时候，`self.maxEndDate`和`self.minEndDate`、`endDate`当前具体的值是多少

比如：
`minimumDate`是`2015-05`
`maximumDate`是`2020-10`
`datePicker.setDate`的值是`2017-08`

当前界面显示的并不是`2017-08`，这样的问题

就是出现不正确的时候，当前的 `maximumDate`、`minimumDate`、`datePicker.setDate`的具体值是多少

**Comment by OCAndSwift** [comment]
可能是第一条我没描述清楚 我列举实例来说明
比如我初始值一个date = 2018-01  (最大值加六个月)
那我需要设置的minimumDate = 2018-02, maximumDate=2018-07 但是我点击视图显示的时候他是可以直接显示到12月份 不是具体值产品这样的问题 只要我的maximumDate没超过12月份 代表没跨年 这时候点击选择的时候就会显示1月到12月份

但是设置date = 2018-10   minimumDate = 2018-11, maximumDate=2019-05
这时候就会显示两个年份2017 2018 但这个时候2018下的月份就只显示到1-5月份数据 这样跨年是正常的

**Comment by OCAndSwift** [comment]
选中日期= 2018-01-28 06:59:18 +0000 第一个控件的值
最小值= 2018-02-28 06:59:18 +0000
最大值= 2018-07-28 06:59:18 +0000  这个是第二个控件的最大值 但是显示的时候显示到2018的12月份的

**Comment by xiaozhuxiong121** [comment]
在`1.5.7`版本中修复了，`pod update`试试

**Comment by xiaozhuxiong121** [comment]
我刚看了一下，在`1.5.7`版本中没有推送上去，我推送到了`1.5.8`版本中，你试试，看好了没

**Comment by OCAndSwift** [comment]
时间范围问题好了 谢谢. 还想请教一下 这个库支持同时展示选择开始时间和结束时间吗?

**Comment by xiaozhuxiong121** [comment]
暂时还不支持

**Comment by OCAndSwift** [comment]
好的 期待你的持续更新

**Comment by xiaozhuxiong121** [comment]
好的。
