### ISSUE TITLE
有没有方法添加一个半透明背景

### ISSUE THREAD

**Issue by heyehao2008** [xiaozhuxiong121/PGDatePicker#21]
个人认为需要添加一个半透明背景的方法。好多设计图弹选择器都加了一个黑色半透明遮罩。

比如增加一个show方法，在用一个属性可以改变遮罩的颜色
- (void)showWithShadeBackgroud:(BOOL)isShowShade;

**Comment by xiaozhuxiong121** [comment]
非常感谢，在`1.5.6`版本中已添加
