### ISSUE TITLE
低于10的数子前面的0在刚开始是有的, 过一会儿消失了,能不能可以选在前面带不带0

### ISSUE THREAD

**Issue by liyanfei1004774105** [xiaozhuxiong121/PGDatePicker#24]

**Comment by xiaozhuxiong121** [comment]
时分秒，小于`10`默认是带`0`

1、过一会儿消失了是什么意思？
2、能不能可以选在前面带不带0，这句话又是什么意思呢？

不太明白你的问题跟需求，请说的尽量详细点

**Comment by liyanfei1004774105** [comment]
1,就是表示时间的的数字 一开始显示的是 01,02,03...当改变月份后,变成了  1,2,3....这样
![img_2038](https://user-images.githubusercontent.com/19235739/33648308-34534c6a-da94-11e7-9120-d90912dc6f3d.PNG)
![img_2039](https://user-images.githubusercontent.com/19235739/33648309-3486b96a-da94-11e7-8391-2a1bd422d1fd.PNG)
2,我是希望表示月,日,和时的数字,前面的0带不带可以自己选择,这样结果不用再做处理

**Comment by xiaozhuxiong121** [comment]
你当前的版本是多少

**Comment by jiading-yang** [comment]
让他自己修改一下源码就好，就是自己处理一下分钟的显示。做开发连个源码都不能修改还做什么开发
