### ISSUE TITLE
日期最大最小有问题

### ISSUE THREAD

**Issue by lovely71** [xiaozhuxiong121/PGDatePicker#25]
例如设置 2017-9-30最小 2017-10-2最大 ,初始化时日期列显示所有,在滚动第二列后才显示正确的日期选择列
另外, 调用消失后不进行初始化仅调用show方法无效,需要重新初始化或自己修改代码,忘以后完善

**Comment by liyanfei1004774105** [comment]
我有同样的问题,不知道是不是版本问题

**Comment by lovely71** [comment]
追加,只要min-maxdate中不包含当前日期,会导致年份月份选择出现问题,月份和年份跳过选中方法,导致日期列无法刷新数据源
    datePicker.minimumDate = [formatter dateFromString:@"2015-9-30"];
    datePicker.maximumDate = [formatter dateFromString:@"2017-10-1"];

**Comment by xiaozhuxiong121** [comment]
更新到`1.5.10`版本试试

**Comment by lovely71** [comment]
datePicker.minimumDate = [formatter dateFromString:@"2015-9-30"];
datePicker.maximumDate = [formatter dateFromString:@"2015-10-1"];
代码如上,1.5.10版本中初始化后9月出现了31号

**Comment by xiaozhuxiong121** [comment]
推到了`1.5.11`上，你在试试还有问题没

**Comment by lovely71** [comment]
完美解决问题,提一个小改善,希望有时间解决吧
date.minDate = [formatter dateFromString:@"2015-9-30"];
date.maxDate = [formatter dateFromString:@"2016-10-02"];
设置如上时,初始化自动选中2016-01-01;
date.minDate = [formatter dateFromString:@"2015-9-30"];
date.maxDate = [formatter dateFromString:@"2016-10-02"];
这时自动选中2017-01-06,应该是由于年份与今天相同,所以还是进了设置选中的判断,但是month判断是否在monthlist的时候为false,所以默认值1

更新的非常快,赞

**Comment by lovely71** [comment]
不好意思还有有个bug
date.minDate = [formatter dateFromString:@"2015-9-30"];
    date.maxDate = [formatter dateFromString:@"2016-12-02"];
这时自动选中2016-01-01,点击确定,日期为输出为2015-11-30

**Comment by xiaozhuxiong121** [comment]
没事的，更新到`1.5.12`试试

**Comment by lovely71** [comment]
ok了
