### ISSUE TITLE
CocoaPods安装,语言没有本地化,年月日 显示英文

### ISSUE THREAD

**Issue by liyanfei1004774105** [xiaozhuxiong121/PGDatePicker#26]

**Comment by liyanfei1004774105** [comment]
![img_d23f60ba28a2-1](https://user-images.githubusercontent.com/19235739/33648653-dfb5693e-da95-11e7-8d00-4789f096c8af.jpeg)
大神帮忙解决一下,我已经要用这个了

**Comment by xiaozhuxiong121** [comment]
![42be3b30-5997-433c-979a-f7ff22739c5d](https://user-images.githubusercontent.com/7292110/33648937-f8142c6c-da96-11e7-8e3d-dcb90300bdae.png)
这里的设置是啥样的？

**Comment by liyanfei1004774105** [comment]
![2017-12-06 3 20 37](https://user-images.githubusercontent.com/19235739/33649479-0b8832dc-da99-11e7-9165-604f5ed721e7.png)

**Comment by xiaozhuxiong121** [comment]
查看project下的Localizations

**Comment by liyanfei1004774105** [comment]
![2017-12-06 3 41 34](https://user-images.githubusercontent.com/19235739/33650232-09b134e2-da9c-11e7-8706-be850d67c0e2.png)

**Comment by xiaozhuxiong121** [comment]
还是不对吗？

**Comment by liyanfei1004774105** [comment]
还是不对

**Comment by xiaozhuxiong121** [comment]
你当前的版本是多少

**Comment by liyanfei1004774105** [comment]
Using PGDatePicker (1.5.9)

**Comment by xiaozhuxiong121** [comment]
方便的话，留个你的QQ联系方式，我看看

**Comment by liyanfei1004774105** [comment]
1004774105   麻烦了啊
