### ISSUE TITLE
当前时间定位错误

### ISSUE THREAD

**Issue by liyanfei1004774105** [xiaozhuxiong121/PGDatePicker#27]
设置当前时间  2017-12-06 03:16:00 定位到了2017-12-06 15:16
<img width="333" alt="2017-12-06 3 17 12" src="https://user-images.githubusercontent.com/19235739/33649402-d0207c36-da98-11e7-89b9-3edc29ac6782.png">

**Comment by xiaozhuxiong121** [comment]
15点就是3点啊，24小时制啊

**Comment by liyanfei1004774105** [comment]
我给的时间是03:16,我如果给15:16才能定位到15:16吧,这样我上午的时间没法定位了

**Comment by xiaozhuxiong121** [comment]
你是不是不是最新版本，我本地测试是可以的

```
PGDatePicker *datePicker = [[PGDatePicker alloc]init];
datePicker.delegate = self;
[datePicker show];
datePicker.datePickerType = PGPickerViewType3;
datePicker.datePickerMode = PGDatePickerModeDateHourMinuteSecond;

NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
dateFormatter.dateFormat = @"yyyy-MM-dd HH:mm:ss";
NSDate *date = [dateFormatter dateFromString: @"2017-12-06 03:16:00"];
[datePicker setDate:date animated:true];
```
![87ebbfe4-b036-4d9e-a69b-3df055743c91](https://user-images.githubusercontent.com/7292110/33649996-209e47c2-da9b-11e7-9058-0c52c3817300.png)

**Comment by liyanfei1004774105** [comment]
不好意思,可能是我的时间格式有问题,他定位的是当前时间不是我给他的时间, 谢谢了
