### ISSUE TITLE
如果日期选择器可以和上面的工具条独立开来可能更加方便

### ISSUE THREAD

**Issue by Homin818** [xiaozhuxiong121/PGDatePicker#28]
如果日期选择器可以和上面的工具条独立开来可能更加方便

**Comment by xiaozhuxiong121** [comment]
谢谢，非常好的主意，会抽空改改

**Comment by xiaozhuxiong121** [comment]
在`2.0`版本中，将`PGDatePicker`彻底分离开来，可以单独设置自己的样式，可以下载demo，参考`PGDatePickManager`类
但是`2.0`版本变化比较大，要升级会报错，可以参考使用方法适当的改下
