### ISSUE TITLE
为啥我转成NSDate格式的时候，会出现时差差8小时的情况？而你的demo就没事儿呢

### ISSUE THREAD

**Issue by q32784307** [xiaozhuxiong121/PGDatePicker#29]

**Comment by xiaozhuxiong121** [comment]
你怎么转的，贴一下代码

**Comment by q32784307** [comment]
NSCalendar *gregorian = [[NSCalendar alloc]initWithCalendarIdentifier:NSCalendarIdentifierGregorian];
    NSDate *date = [gregorian dateFromComponents:dateComponents];

莫名奇妙的又好了...
