### ISSUE TITLE
日期和时间可以加个循环选择的功能吗？

### ISSUE THREAD

**Issue by Jonzzs** [xiaozhuxiong121/PGDatePicker#30]
现在很多日期选择都是可以循环选择的，希望能加这个功能，写的很棒！

**Comment by Yang4an** [comment]
啥时候能加上循环滚动呢？

**Comment by lennondong** [comment]
今天也遇到这个问题了，确实日期选择不能循环，从59要改成00，真的是要拨弄半天。
个人认为这个优先级应该是：高。
请作者能优先更新。

**Comment by Eric1143** [comment]
希望尽快加上此功能

**Comment by xiaozhuxiong121** [comment]
Hi all
循环功能已经加上，更新到2.6.4版本
`pod update`
使用：
```
datePicker.isCycleScroll = true;
```
