### ISSUE TITLE
setDate 跳转的不对

### ISSUE THREAD

**Issue by zhiaiing** [xiaozhuxiong121/PGDatePicker#32]
![img_0633](https://user-images.githubusercontent.com/15857315/34507638-0d7347f4-f073-11e7-98cd-9971ee887dd0.JPG)
![123](https://user-images.githubusercontent.com/15857315/34507640-13b6d6da-f073-11e7-814d-9e7ea43d5968.png)

**Comment by xiaozhuxiong121** [comment]
把你的代码在我的demo上运行了一下，是没有问题的，你更新到最新版本试试

**Comment by zhiaiing** [comment]
setupPickerView 方法里   

年份相同，没有判断月份是否 小于最小minimumDate的月份

![111](https://user-images.githubusercontent.com/15857315/34863806-4248374c-f7ac-11e7-8d19-880d421d36d5.png)

**Comment by zhiaiing** [comment]
这样试下
![123](https://user-images.githubusercontent.com/15857315/34864746-bbdfc986-f7b0-11e7-966b-7957f858baf5.png)
![img_0651](https://user-images.githubusercontent.com/15857315/34864749-bd2186fe-f7b0-11e7-981b-1956c72ae8e9.JPG)

**Comment by zhiaiing** [comment]
这样试下
![Uploading 123.png…]()
![Uploading IMG_0651.JPG…]()

**Comment by zhiaiing** [comment]
这样试下
![1111](https://user-images.githubusercontent.com/15857315/34864939-89c6a6bc-f7b1-11e7-8db4-42a754fb0996.png)
![2222](https://user-images.githubusercontent.com/15857315/34864949-9147d438-f7b1-11e7-920f-8095157e748d.JPG)

**Comment by zhiaiing** [comment]
![qqq](https://user-images.githubusercontent.com/15857315/34865653-84b2b0e6-f7b4-11e7-8276-300862f70183.png)
