### ISSUE TITLE
怎么改变PGPickerView的位置

### ISSUE THREAD

**Issue by YUHG412** [xiaozhuxiong121/PGDatePicker#33]
1，怎么改变PGPickerView的位置， 想把它放在中间
2，现在默认是选择第三行，怎么把它修改成第一行，如图把选中的那里放在箭头指向位置
3，江湖救急，非常感谢
![image](https://user-images.githubusercontent.com/29453499/34511735-9c84f792-f098-11e7-92db-31a1189bac68.png)

**Comment by xiaozhuxiong121** [comment]
` [datePicker setDate:date animated:true];`

**Comment by YUHG412** [comment]
留个方式吧，大神：QQ 963852006

**Comment by xiaozhuxiong121** [comment]
在`2.0`版本中，将`PGDatePicker`彻底分离开来，可以单独设置自己的样式，可以下载demo，参考`PGDatePickManager`类
但是`2.0`版本变化比较大，要升级会报错，可以参考使用方法适当的改下
