### ISSUE TITLE
设置minimumDate和maximumDate后的bug

### ISSUE THREAD

**Issue by AYJk** [xiaozhuxiong121/PGDatePicker#34]
你好，我发现设置时日周 时分这里，设置他的minimumDate和maximumDate后，滑动月日和时之后，他的分会出现问题，截图如下
![1515415605962](https://user-images.githubusercontent.com/16362013/34671330-24507050-f4b5-11e7-91ab-434aacb5229e.jpg)

![wechatimg493](https://user-images.githubusercontent.com/16362013/34671383-51bfc874-f4b5-11e7-9fae-d7caf1c29f6e.jpeg)
![wechatimg494](https://user-images.githubusercontent.com/16362013/34671384-51fa09b2-f4b5-11e7-83e8-3dc16f326059.jpeg)
![wechatimg495](https://user-images.githubusercontent.com/16362013/34671385-5227aca0-f4b5-11e7-853a-cdc303d0b46f.jpeg)

只能选择一个分了。_minuteList里面只有一个元素了。

**Comment by xiaozhuxiong121** [comment]
在`2.0.1`版本中更新了，`pod update`，试试
