### ISSUE TITLE
pod 出错

### ISSUE THREAD

**Issue by wlingf** [xiaozhuxiong121/PGDatePicker#35]
[!] Unable to satisfy the following requirements:

- `PGDatePicker (>= 2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `PGDatePicker (>= 2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by xiaozhuxiong121** [comment]
pod repo update试试

**Comment by wlingf** [comment]
标题那栏的背景色支持修改吗  文档没看到相关修改信息

**Comment by xiaozhuxiong121** [comment]
暂时没有，你可以先修改下源码，在下个版本我会加上

**Comment by wlingf** [comment]
还有为什么会显示2018Y 01M 而不是年 月

**Comment by xiaozhuxiong121** [comment]
模拟器的话，系统语言调成中文

**Comment by wlingf** [comment]
那能只显示2108  这样吗

**Comment by xiaozhuxiong121** [comment]
什么意思？

**Comment by wlingf** [comment]
不带年月日这样的文字

**Comment by wlingf** [comment]
Installing PGDatePicker 2.0 (was 1.4.3)
Installing PGPickerView (1.2.1)  版本更小了

**Comment by wlingf** [comment]
已解决
