### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by wmc233** [xiaozhuxiong121/PGDatePicker#39]
你好，我想问下，我安装PGDatePicker成功了，但是在import的时候为什么会报错，说PGDatePicker不存在啊

**Comment by xiaozhuxiong121** [comment]
在`Podfile`里面添加`use_frameworks!`试试

**Comment by wmc233** [comment]
嗯，我加了，但是import之后，又显示这样的报错   Could not build Objective-C module 'PGDatePicker'
是还要改哪里吗？

**Comment by xiaozhuxiong121** [comment]
是cocoapods集成的吗？我的swiftDemo你下载下参考一下

**Comment by wmc233** [comment]
已经下载了，我还是再看看吧，感谢大神及时的回复：）
