### ISSUE TITLE
对headerView和picker和dissmissView 用weak修饰导致选择年月模式时在ios10 block中removefromsuperView闪退  

### ISSUE THREAD

**Issue by 15394537523** [xiaozhuxiong121/PGDatePicker#4]
我用strong修饰后 不在闪退

**Comment by xiaozhuxiong121** [comment]
是我这边的问题吗？

**Comment by 15394537523** [comment]
en

**Comment by 15394537523** [comment]
你用模拟器测试下 选择年月模式 会造成对weak对象多进行了一次release导致崩溃  手动添加的控件要用strong修饰 xib则是weak 你可以查下资料

**Comment by xiaozhuxiong121** [comment]
我还是没有听明白，```PGDatePicker```不需要加在任何控件上，```[datePicker show];```就可以显示出来，可以留个QQ，发个简单的demo，我看下么

**Comment by 15394537523** [comment]
就是你的官方demo  你官方demo就闪退了  因为你对着两个视图用weak修饰了
![image](https://user-images.githubusercontent.com/18565140/32032656-d9403108-b9cd-11e7-904d-753add74f2d8.png) 我改为strong了
导致在这里调用后 又对weak对象进行了一次realease 崩溃
![image](https://user-images.githubusercontent.com/18565140/32032707-2172a712-b9ce-11e7-9c14-dacabda8568e.png)

**Comment by xiaozhuxiong121** [comment]
我已经指向创建好对象的句柄就没有必要用```strong```修饰了，能说下你的运行环境么，我使用的10.3.1的模拟器也没有出现崩溃现象

**Comment by 15394537523** [comment]
qq: 674149625  我也是10.3.3  6sp

**Comment by xiaozhuxiong121** [comment]
已解决。
