### ISSUE TITLE
滚动时，有残留，但是运行您的DEMO，没有任何问题。不知道为何

### ISSUE THREAD

**Issue by tanranran** [xiaozhuxiong121/PGDatePicker#40]
版本：通过pod 'PGDatePicker', '>= 2.0'引入
用法：
`    PGDatePickManager *datePickManager=[[PGDatePickManager alloc]init];
    datePickManager.cancelButtonTextColor=BLUEPRIMARY;
    datePickManager.confirmButtonTextColor=BLUEPRIMARY;
    datePickManager.isShadeBackgroud=YES;
    PGDatePicker *datePicker = datePickManager.datePicker;
    datePicker.datePickerMode=PGDatePickerModeDateHourMinute;
    datePicker.datePickerType=PGDatePickerType1;
    datePicker.delegate = self;
    datePicker.minimumDate=[NSDate new];
    datePicker.maximumDate=[TimeUtil getFutureDate:100];
    [self.controller presentViewController:datePickManager animated:false completion:nil];`

如图：
![image](https://user-images.githubusercontent.com/5227840/35094761-38708c54-fc81-11e7-8b35-a362f61fef00.png)
![image](https://user-images.githubusercontent.com/5227840/35094916-c22aef48-fc81-11e7-822d-ea847b26467d.png)

**Comment by xiaozhuxiong121** [comment]
设置没有问题 这段代码是不是执行了多次？

**Comment by tanranran** [comment]
@xiaozhuxiong121  可以确定 只执行了一次，能否留个联系方式，我联系下您？

**Comment by xiaozhuxiong121** [comment]
QQ：294194253

**Comment by xiaozhuxiong121** [comment]
已修复
