### ISSUE TITLE
月日周 时分模式下 在设置了 isHiddenMiddleText = NO 后  的显示问题

### ISSUE THREAD

**Issue by huoxiao5** [xiaozhuxiong121/PGDatePicker#41]
首先感谢作者写了个这么好用的控件，大大的赞 👍👍👍👍👍👍👍
今天下载了最新的版本使用demo测试了一下，在月日周时分模式下，设置isHiddenMiddleText = NO 
显示异常了，如图所示
![img1](https://raw.githubusercontent.com/huoxiao5/temptransfer/master/b1-01.png)
![img2](https://raw.githubusercontent.com/huoxiao5/temptransfer/master/b1-02.png)

**Comment by xiaozhuxiong121** [comment]
因为周一直在变化，所以为了美观，弄了这样的效果，在`2.0.3`版本中
![32100487-2270-48da-8729-32892d7ea788](https://user-images.githubusercontent.com/7292110/35149165-09d67d8e-fd50-11e7-8fad-f869ab27eb14.png)

**Comment by huoxiao5** [comment]
感谢作者，这么快就修改了， 赞赞赞赞 👍 👍 👍 👍 👍 👍 👍
