### ISSUE TITLE
关于时分选择

### ISSUE THREAD

**Issue by 06guo** [xiaozhuxiong121/PGDatePicker#42]
打开时间选择，默认显示上一次选中的的时间是
 NSDate *date = [NSDate setHour:10 minute:10];
    [datePicker setDate:date animated:true];
这样么，

**Comment by 06guo** [comment]
我只需要设置时分，但是我这样设置，并不能显示出来之前设置的时间，还是从00：00开始的

**Comment by xiaozhuxiong121** [comment]
我周末修复一下

**Comment by xiaozhuxiong121** [comment]
不好意思，改了一行代码，没有发现，在`2.0.4`版本中更新好了
