### ISSUE TITLE
时间选择有问题

### ISSUE THREAD

**Issue by xhzth709150** [xiaozhuxiong121/PGDatePicker#45]
![c5116a94-e50a-4c9e-b8b8-36597100545a](https://user-images.githubusercontent.com/33826892/35312763-13ddd75e-00f8-11e8-83fb-aa350a4b4fd2.png)
[datePicker setDate:date animated:true];不跳转到对应的时间，差了几个月

**Comment by xiaozhuxiong121** [comment]
不好意思，改了一行代码，没有发现，在`2.0.4`版本中更新好了
