### ISSUE TITLE
日期选择bug

### ISSUE THREAD

**Issue by AlvinBoy** [xiaozhuxiong121/PGDatePicker#47]
操作如下：
当mode为PGDatePickerModeDate时，选择2018年5月31日，当将月份滚动到4月时，日的那一列不跟年月两列对其。

**Comment by xiaozhuxiong121** [comment]
能截个图看下么？

**Comment by AlvinBoy** [comment]
![7dee1d286de4c4765fe93a667279e443](https://user-images.githubusercontent.com/11266920/35377575-aee5af0e-01ea-11e8-9a25-e46830dc14fb.png)

**Comment by AlvinBoy** [comment]
当设置了rowHeight后也会出现这样的情况，年月日都会不居中。

**Comment by xiaozhuxiong121** [comment]
rowHeight确实有点问题，这个可以暂时修改源码，源码里面有对应的高度，可以修改一下，rowHeight这个我有时间了修复一下

你下载我的demo，也有这样的问题么

**Comment by AlvinBoy** [comment]
修改默认高度也不行，你demo中的高度都是以默认高度的倍数来设计的，所以没问题。我感觉PGPickerView有问题。

**Comment by xiaozhuxiong121** [comment]
嗯，对，把相应的倍数改了也是不行么

**Comment by AlvinBoy** [comment]
setDate又不管用了

**Comment by AlvinBoy** [comment]
改相应倍数没问题，但是44这个默认值不能变，而且pickerview的高度不一定是44

**Comment by xiaozhuxiong121** [comment]
setDate你更新到最新版，2.0.4
高度问题，我抽时间看下，最新项目实在太忙了

**Comment by AlvinBoy** [comment]
setDate你更新到最新版，2.0.4 也不行

**Comment by xiaozhuxiong121** [comment]
贴一下你的代码，我看下

**Comment by AlvinBoy** [comment]
你close掉哪个问题后可以了一会，后来又不行了，你是不是又改什么东西了。
self.datePicker.datePickerMode = PGDatePickerModeDate;
    self.datePicker.autoSelected = YES;
    self.datePicker.isHiddenMiddleText = YES;
    self.datePicker.textColorOfSelectedRow = UIColorFromHex(0xca874a);
    self.datePicker.middleTextColor = UIColorFromHex(0xca874a);
    self.datePicker.textColorOfOtherRow = UIColorFromHex(0xcecece);
    self.datePicker.lineBackgroundColor = UIColorFromHex(0xe4e4e4);
    self.datePicker.delegate = self;

**Comment by xiaozhuxiong121** [comment]
没有改的，你把setDate的设置贴一下，如果设置了最大跟最小值的话，也贴一下，或者你把对应的代码放到我的demo里面，看看行不行

**Comment by AlvinBoy** [comment]
[self.datePicker setDate:self.date animated:YES];
定位有时正确，有时不正确。

**Comment by xiaozhuxiong121** [comment]
哎呀，大哥，你把setDate的具体日期以及相关代码放到我demo里面看看行不行

**Comment by xiaozhuxiong121** [comment]
如果说不准确，怎么操作了导致不准确，说清楚一点，我才好修改么，要不然我也是一头雾水，不知怎么下手

**Comment by xiaozhuxiong121** [comment]
新版本已经修复，rowHeight问题，更新一下，试试
