### ISSUE TITLE
iphoneX 下方怎么是这种效果？

### ISSUE THREAD

**Issue by guoyutao** [xiaozhuxiong121/PGDatePicker#49]
![image](https://user-images.githubusercontent.com/11513385/35620535-5b19e56c-06bc-11e8-8093-0812b3e857b4.png)

**Comment by xiaozhuxiong121** [comment]
2.0.6版本吗？

**Comment by guoyutao** [comment]
最近的是2.0.3呀 @xiaozhuxiong121 
![image](https://user-images.githubusercontent.com/11513385/35627142-f57b70d8-06d2-11e8-9594-361a543547bf.png)

**Comment by xiaozhuxiong121** [comment]
`pod update`
![d7c2ca01-833b-4992-bac0-dd88aaf449d4](https://user-images.githubusercontent.com/7292110/35657102-ac8349d8-0735-11e8-81b1-6bffa2e075a9.png)
