### ISSUE TITLE
请教个问题！

### ISSUE THREAD

**Issue by kinghour** [xiaozhuxiong121/PGDatePicker#5]
大神 我想按照你的样式  更改为城市选择器  想把数据换掉 请问应该那个地方开始  我没找到你导入数据的地方。。。。

**Comment by xiaozhuxiong121** [comment]
因为现在依赖性过大，所以改起来应该会很吃力，你可以使用[PGPickerView
](https://github.com/xiaozhuxiong121/PGPickerView)试试
