### ISSUE TITLE
日期选择回调函数返回值有问题

### ISSUE THREAD

**Issue by Azraeltulips** [xiaozhuxiong121/PGDatePicker#51]
日期选择回调函数返回值dateComponents在选择一月的时候，month为0。而且，选择日期时必须滚动一下月，不然会出错。我在2018.02.01这天试着值滚动年到2017，结果输出结果是2017.02.01

**Comment by xiaozhuxiong121** [comment]
你是最新的`2.0.6`版本吗，如果是的话贴一下你的代码，我看看
