### ISSUE TITLE
如何兼容国外？

### ISSUE THREAD

**Issue by shineFoyMylove** [xiaozhuxiong121/PGDatePicker#56]
跟着系统语言走，当是英语的时候，显示Y/M/D H:M:S, 可是国外的习惯不是，27 Feb 2018 10:30  或者 Feb 27 2017 10:30 ，能帮忙给个思路吗，怎么改

**Comment by xiaozhuxiong121** [comment]
dateFormat = @"dd MM yyyy HH:mm"
