### ISSUE TITLE
发现个小问题

### ISSUE THREAD

**Issue by ZhaoBinHua** [xiaozhuxiong121/PGDatePicker#6]
在执行show方法之前设定titleLabel属性时无效，原因是在show之前没创建相应的控件。还有titleColorForOtherRow该属性设置无效，望及时解决。

**Comment by xiaozhuxiong121** [comment]
谢谢反馈，已经修复，请更新```pod update```
```
pod 'PGDatePicker', '>= 1.2.1'
```

**Comment by ZhaoBinHua** [comment]
您好，titleColorForOtherRow该属性仍然无效，在设置titleColorForOtherRow和titleColorForSelectedRow之后，显示都是titleColorForSelectedRow

**Comment by xiaozhuxiong121** [comment]
已修复，请更新```pod update```
```
pod 'PGDatePicker', '>= 1.4.0'
```
