### ISSUE TITLE
默认时间设置问题

### ISSUE THREAD

**Issue by RenChuanChuan** [xiaozhuxiong121/PGDatePicker#60]
设置默认时间，动画要关闭才准确，要是开启动画，滚动不准确，会滚到前几年。

`/**
 年月日
 */
- (IBAction)dateHandler:(id)sender {
    PGDatePickManager *datePickManager = [[PGDatePickManager alloc]init];
    datePickManager.isShadeBackgroud = true;
    PGDatePicker *datePicker = datePickManager.datePicker;
    datePicker.delegate = self;
    datePicker.datePickerType = PGPickerViewType1;
    datePicker.isHiddenMiddleText = false;
    datePicker.datePickerMode = PGDatePickerModeDate;
    [self presentViewController:datePickManager animated:false completion:nil];
    
    datePicker.minimumDate = [NSDate setYear:1900 month:1 day:1];
    datePicker.maximumDate = [NSDate setYear:2100 month:12 day:31];

    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
    dateFormatter.dateFormat = @"yyyy-MM-dd";
    NSDate *date = [dateFormatter dateFromString: @"2018-03-14"];
    [datePicker setDate:date animated:NO];   /** 这个动画设置滚动不准确 */
}`

**Comment by xiaozhuxiong121** [comment]
更新到最新的2.1.0试试。我把你的这段代码放到我的demo里面不会出现问题，你看看是不是版本低了

**Comment by xiaozhuxiong121** [comment]
`pod update`到`2.2.1`版本试试
