### ISSUE TITLE
线条高度

### ISSUE THREAD

**Issue by RenChuanChuan** [xiaozhuxiong121/PGDatePicker#61]
upLine 和 downLine 高度不一样，上线高度1，下线高度0.5，why...

![image](https://user-images.githubusercontent.com/8433532/37440307-25f03d22-2837-11e8-9aba-fde8a38c6257.png)

**Comment by xiaozhuxiong121** [comment]
真机吗？

**Comment by RenChuanChuan** [comment]
模拟器和真机都是这样，有没有QQ交流下 ：）

**Comment by xiaozhuxiong121** [comment]
294194253

**Comment by DogTwoChen** [comment]
解决了吗,同遇到....

**Comment by leaolei** [comment]
没有






------------------ 原始邮件 ------------------
发件人: GodTwoChen <notifications@github.com>
发送时间: 2019年5月30日 09:52
收件人: xiaozhuxiong121/PGDatePicker <PGDatePicker@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[xiaozhuxiong121/PGDatePicker] 线条高度 (#61)




解决了吗,同遇到....

**Comment by LiuSky** [comment]
这个问题都没有解决作者为什么就关闭了？
