### ISSUE TITLE
设置了时间范围后，时间范围外的时间还是能选到，定位时间准确但是范围是错的

### ISSUE THREAD

**Issue by ruyulin** [xiaozhuxiong121/PGDatePicker#62]
PGDatePickManager *datePickManager = [[PGDatePickManager alloc]init];
    datePickManager.isShadeBackgroud = true;
    datePickManager.titleLabel.text = @"订餐日期选择";
    PGDatePicker *datePicker = datePickManager.datePicker;
    datePicker.delegate = self;
    datePicker.datePickerType = PGPickerViewType2;
    datePicker.datePickerMode = PGDatePickerModeDateHourMinute;
    [self presentViewController:datePickManager animated:false completion:nil];
    
    NSDate *date =[NSDate date];
    NSDateFormatter *formatter = [[NSDateFormatter alloc]init];
    [formatter setDateFormat:@"yyyy"];
    NSInteger currentYear=[[formatter stringFromDate:date] integerValue];
    [formatter setDateFormat:@"MM"];
    NSInteger currentMonth=[[formatter stringFromDate:date]integerValue];
    [formatter setDateFormat:@"dd"];
    NSInteger currentDay=[[formatter stringFromDate:date] integerValue];
    [formatter setDateFormat:@"HH"];
    NSInteger currentHours=[[formatter stringFromDate:date] integerValue];
    [formatter setDateFormat:@"mm"];
    NSInteger currentMinutes=[[formatter stringFromDate:date] integerValue];
    [datePicker setDate: date animated:YES];
    datePicker.minimumDate = [NSDate setYear:currentYear month:currentMonth day:currentDay hour: currentHours+3 minute:currentMinutes];
    datePicker.maximumDate = [self getPriousorLaterDateFromDate:[NSDate date] withMonth: 1];
![4e7b1010-3177-438a-a166-9f773e2b2976](https://user-images.githubusercontent.com/22791753/37634073-ea771c78-2c2f-11e8-89cc-15b2f6019ab5.png)

**Comment by xiaozhuxiong121** [comment]
pod update到2.2.1版本试试

**Comment by ruyulin** [comment]
我刚才试了试2.2.1，是可以的，已解决我提出的问题
