### ISSUE TITLE
IOS 11 设置date后，滚轮滚动出错。

### ISSUE THREAD

**Issue by klbest1** [xiaozhuxiong121/PGDatePicker#64]
@implementation PGPickerTableView
- (instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style {
    if (self = [super initWithFrame:frame style:style]) {
        self.separatorInset = UIEdgeInsetsMake(0, 0, 0, 0);
        self.tableFooterView = [UIView new];
        self.separatorStyle = UITableViewCellSeparatorStyleNone;
        self.backgroundColor = [UIColor clearColor];
        self.estimatedRowHeight = 0;
        self.estimatedSectionHeaderHeight = 0;
        self.estimatedSectionFooterHeight = 0;
    }
    return self;
}

这里需要加上：
        self.estimatedRowHeight = 0;
        self.estimatedSectionHeaderHeight = 0;
        self.estimatedSectionFooterHeight = 0;
不然IOS 11上滚动会出错。

**Comment by xiaozhuxiong121** [comment]
你用的版本是多少

**Comment by klbest1** [comment]
我直接 
   pod 'PGDatePicker'
这个默认应该安装的是最新的吧？
这1、2周才加的

**Comment by xiaozhuxiong121** [comment]
我用的也是iOS11没有出现问题，版本大于2.1.0的应该是没有问题的
