### ISSUE TITLE
全月全日選項

### ISSUE THREAD

**Issue by zkil** [xiaozhuxiong121/PGDatePicker#65]
如果可以选择全年或全日功能就好了，还有取消按钮事件，如果自己加要怎么加

**Comment by xiaozhuxiong121** [comment]
能具体描述一下么
1、全月全日是只有选择月日的功能吗
2、取消按钮事件，要自己手动添加？不明白什么意思

**Comment by zkil** [comment]
比如我做一个根据日期筛选数据功能，我选择了样式年月日，那么我只能选择指定的年月日，如果在年月日列的一个分别加上 全年/全月/全日  ，当日这一列选"全日"了，则忽略"日", 相当于选择了整日，以此类推。
取消按钮事件我刚才通过修改代码已经有了，就是界面点取消有一个回调

**Comment by xiaozhuxiong121** [comment]
选了日就是全日啊，不明白什么意思
