### ISSUE TITLE
发现一个功能上的问题

### ISSUE THREAD

**Issue by tandepeng** [xiaozhuxiong121/PGDatePicker#7]
在设置样式过程中， 选中行的颜色与非选中行的颜色并没有效果区分
    datePicker.titleColorForSelectedRow = [UIColor redColor];
    datePicker.titleColorForOtherRow = [UIColor blackColor];

**Comment by xiaozhuxiong121** [comment]
谢谢反馈，已经修复，请更新```pod update```
```
pod 'PGDatePicker', '>= 1.4.0'
```
