### ISSUE TITLE
您好，在使用“年月日时分”这个枚举时，我规定了minimumDate和maximumDate，出现了小时默认选中了空白

### ISSUE THREAD

**Issue by LYluyu** [xiaozhuxiong121/PGDatePicker#72]
您好，在使用“年月日时分”这个枚举时，我规定了minimumDate和maximumDate，出现了小时默认选中了空白，代码如下

PGDatePickManager *datePickManager = [[PGDatePickManager alloc]init];
    datePickManager.isShadeBackgroud = true;
    PGDatePicker *datePicker = datePickManager.datePicker;
    datePicker.delegate = self;
    datePicker.datePickerType = PGPickerViewType2;
    datePicker.datePickerMode = PGDatePickerModeDateHourMinute;
	NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
	dateFormatter.dateFormat = @"yyyy-MM-dd HH:mm:ss";
	datePicker.minimumDate = [dateFormatter dateFromString: @"2018-04-17 18:00:00"];
	datePicker.maximumDate = [dateFormatter dateFromString: @"2018-04-18 00:00:00"];
    [self presentViewController:datePickManager animated:false completion:nil];

**Comment by xiaozhuxiong121** [comment]
在`2.4.2`版本中修复了，`pod update `试试
