### ISSUE TITLE
您好，在使用“年月日时分”这个枚举时，我规定了minimumDate和maximumDate，当当前时间的分在minimumDate和maximumDate的分之外，分钟列数据为空，需要滚动才可以出现

### ISSUE THREAD

**Issue by LYluyu** [xiaozhuxiong121/PGDatePicker#73]
现在出现了另外一个问题，在使用“年月日时分”这个枚举时，我规定了minimumDate和maximumDate，当当前时间的分在minimumDate和maximumDate的分之外，分钟列数据为空，需要滚动才可以出现；
比如当前时间为 2018-04-27 10:16，minimumDate为2018-04-26 09:00:00，maximumDate为2018-04-26 09:06:00，即出现，代码如下:
PGDatePickManager *datePickManager = [[PGDatePickManager alloc]init];
    datePickManager.isShadeBackgroud = true;
    PGDatePicker *datePicker = datePickManager.datePicker;
    datePicker.delegate = self;
    datePicker.datePickerType = PGPickerViewType2;
    datePicker.datePickerMode = PGDatePickerModeDateHourMinute;
	NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
	dateFormatter.dateFormat = @"yyyy-MM-dd HH:mm:ss";
	datePicker.minimumDate = [dateFormatter dateFromString: @"2018-04-26 09:00:00"];
	datePicker.maximumDate = [dateFormatter dateFromString: @"2018-04-26 09:06:00"];
    [self presentViewController:datePickManager animated:false completion:nil];

**Comment by xiaozhuxiong121** [comment]
`pod update`到`2.4.3`试试
