### ISSUE TITLE
 [datePicker setDate:date animated:true]   没有进行 '日' 的联动，希望作者能够解决

### ISSUE THREAD

**Issue by CreazyHeart** [xiaozhuxiong121/PGDatePicker#77]
NSDateFormatter *dateFormatter = [[NSDateFormatter alloc]init];
    dateFormatter.dateFormat = @"yyyy-MM-dd"; 
    NSDate *date = [dateFormatter dateFromString: @"2018-04-04"];
    [datePicker setDate:date animated:true];

选择年月日 ， 设置默认日期后，4月会出现 31日，

**Comment by xiaozhuxiong121** [comment]
pod update 到`2.4.4`试试
