### ISSUE TITLE
开头和结尾还空着一行, 能不能去掉

### ISSUE THREAD

**Issue by AlvinBoy** [xiaozhuxiong121/PGDatePicker#78]

**Comment by xiaozhuxiong121** [comment]
什么意思，发个截图，再把相关代码贴一下

**Comment by AlvinBoy** [comment]
<img width="258" alt="309363f0-f250-45f8-bc4f-16f9cefafeca" src="https://user-images.githubusercontent.com/11266920/39902220-907e4748-54ff-11e8-8ef7-946b222eaffc.png">
@xiaozhuxiong121

**Comment by xiaozhuxiong121** [comment]
贴代码看下
