### ISSUE TITLE
使用遇到的问题

### ISSUE THREAD

**Issue by Zhou1008** [xiaozhuxiong121/PGDatePicker#83]
当选择月、日的时候，滑到最后多一行空的
![e684e775-7115-4b21-b61e-df0e4239b001](https://user-images.githubusercontent.com/17609801/40347488-1327648c-5dd3-11e8-8e74-c1325d2bafdd.png)

**Comment by xiaozhuxiong121** [comment]
是最新版本吗？，贴一下代码
