### ISSUE TITLE
发现一个设置默认选中时间但是显示不正确的bug

### ISSUE THREAD

**Issue by 328784352** [xiaozhuxiong121/PGDatePicker#89]
我设置minimumDate是今天，但是选中时间是未来时间，导致小时数组和分钟数组不包含今天过去的时间，导致显示错误

**Comment by xiaozhuxiong121** [comment]
贴一下代码

**Comment by 328784352** [comment]
self.schedulePicker.maximumDate = [NSDate dateWithDaysFromNow:356*10];//未来10年
self.schedulePicker.minimumDate = [NSDate dateWithDaysBeforeNow:0];//现在时间[self.schedulePicker setDate:currentDate];
[self presentViewController:mindTimePickManager animated:false completion:nil];

**Comment by 328784352** [comment]
self.schedulePicker.datePickerMode = PGDatePickerModeDateHourMinute;
currentDate 可以随便设置一个在范围里面的，但是时、分要早于今天得，就会出问题

**Comment by xiaozhuxiong121** [comment]
你这个有问题吧，最小时间已经是当前时间了，`[self.schedulePicker setDate:currentDate];`还要早于当前时间，这不是有问题么

**Comment by 328784352** [comment]
年月日不小于，但是时跟分小于，例如最小时间是2018年6月8日18点26  选中时间是2018年6月9日 18点26之前就会有问题

**Comment by xiaozhuxiong121** [comment]
`2.4.6`版本中修复了，更新试试

**Comment by 328784352** [comment]
好的~
