### ISSUE TITLE
能不能手動更改語言？

### ISSUE THREAD

**Issue by Danie1s** [xiaozhuxiong121/PGDatePicker#95]
可以開放一個api來設置嗎？

**Comment by Danie1s** [comment]
你的文檔寫著

> 语言跟着手机系统语言走，默认有英文，中文，繁体中文，如果是模拟器的话，将模拟器的系统语言改成中文即显示中文

我現在要做一個香港的項目，需要可以在app裡面手動更改語言，而不是去系統裡面更改。所以想你增加一個更改語言的功能

**Comment by xiaozhuxiong121** [comment]
在`2.5.2`版本中添加了，`pod update`试试
设置`datePicker.language`具体怎么设置可以查看`language`的注解

**Comment by ychmun** [comment]
> 在`2.5.2`版本中添加了，`pod update`试试
> 
> 设置`datePicker.language`具体怎么设置可以查看`language`的注解
